blank_issues_enabled: false
contact_links:
  - name: Soporte por la comunidad
    url: https://discord.gg/AsqX8fkW2k
    about: Sugiera cualquier idea, problema, o reporte que tenga utilizando la comunidad discord.
